# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Inovia Blog"
description: > # this means to ignore newlines until "email:"
   Digressions technologiques par Kadda SAHNINE

email: ksahnine@gmail.com
#blog logo
#logo: "/assets/images/df_logo.jpg"
logo: "/assets/images/ks.png"
# blog cover
#cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
cover: "http://www.kylemarcus.com/wp-content/uploads/2014/02/code-1038x576.jpg"

name: 'Kadda SAHNINE'
author: 'Kadda SAHNINE'
author_image: "/assets/images/kad.png"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ksahnine
    desc: Suivez moi sur Twitter
    share_url: http://twitter.com/ksahnine
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ksahnine
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
