# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Inovia Blog"
description: > # this means to ignore newlines until "email:"
   Excursions technologiques par Kadda SAHNINE

email: ksahnine@gmail.com
#blog logo
logo: "/assets/images/ks.png"
# blog cover
cover: "/assets/images/ZX81-closeup.jpg"

name: 'Kadda SAHNINE'
author: 'Kadda SAHNINE'
author_image: "/assets/images/kad.png"

paginate:	5

url: "http://ksahnine.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ksahnine
    desc: Suivez moi sur Twitter
    share_url: http://twitter.com/ksahnine
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	http://fr.linkedin.com/in/ksahnine
    desc: Voir mon profil Linkedin
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/ksahnine
    desc:	Suivez moi sur github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
